### ISSUE TITLE
Reconnect on lost connection to asterisk

### ISSUE THREAD

**Issue by megapearl** [cyberjacob/hass-asterisk#3]
Hi,

Is it possible to reconnect homeassistant to asterisk when the connection is lost? (due to server reboot, or asterisk restart) ?
When the connection is down your sensor stays at 'disconnected' and does not try to reconnect by itself.
I need to restart homeassistant to get it connected again.

Thanks in advance!

Best Regards,
Donald.

**Comment by girlpunk** [comment]
Hi,

Sorry for the delay, haven't been around for a while.

Thanks for the report, should be fixed by #4. Could you give this a try and see if it fixes it.

Thanks
